-- 코드를 입력하세요
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에서
-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들
-- 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력
-- 결과는 월을 기준으로 오름차순 정렬하고, 월이 같다면 자동차 ID를 기준으로 내림차순 정렬

-- 단. 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외
-- SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS  MONTH, DISTINCT CAR_ID, 
--     COUNT(
--         HISTORY_ID
--     ) AS RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE CAR_ID IN 

-- (
-- SELECT CAR_ID
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
-- GROUP BY CAR_ID
-- HAVING COUNT(CAR_ID) >= 5
-- )

-- GROUP BY TO_NUMBER(TO_CHAR(START_DATE, 'MM')), CAR_ID
-- HAVING COUNT(HISTORY_ID) IS NOT NULL
-- ORDER BY MONTH ASC, CAR_ID DESC;
SELECT MONTH, CAR_ID, COUNT(CAR_ID)
    FROM
    (SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH, CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE CAR_ID IN
                (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-11'
                    GROUP BY CAR_ID
                    HAVING COUNT(*) >= 5)
        AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-11')
    GROUP BY MONTH, CAR_ID
    HAVING COUNT(*) > 0
    ORDER BY MONTH, CAR_ID DESC