SELECT B.TITLE AS TITLE, B.BOARD_ID AS BOARD_ID, R.REPLY_ID AS REPLY_ID, R.WRITER_ID AS WRITER_ID,
R.CONTENTS AS CTENTS,
TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD')
AS CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R 
WHERE B.BOARD_ID = R.BOARD_ID
AND TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;