-- 코드를 입력하세요
SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO INFO, REST_REVIEW REVIEW
WHERE INFO.REST_ID = REVIEW.REST_ID
GROUP BY INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS
HAVING INFO.ADDRESS LIKE '서울%'
ORDER BY AVG(REVIEW.REVIEW_SCORE) DESC, FAVORITES DESC;